// <auto-generated />
namespace IsmsWebApplication.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class morestuff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(morestuff));
        
        string IMigrationMetadata.Id
        {
            get { return "201402060436259_more stuff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
