// <auto-generated />
namespace IsmsWebApplication.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addeddatedatatype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addeddatedatatype));
        
        string IMigrationMetadata.Id
        {
            get { return "201402060539071_added date datatype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
